### ISSUE TITLE
Linking errors

### ISSUE THREAD

**Issue by mrjackbo** [renatoGarcia/icecream-cpp#1]
I was using version 0.1.0 of icecream-cpp for a while, and I have `IC` statements in multiple source files, which are compiled independently (as cmake object libraries) and then linked together into different binaries and shared libraries. This used to work very nicely. Now I upgraded to 0.3.0, recompiled everything, and get linking errors like so:
```
multiple definition of `icecream::detail::show_c_string()'
```

I know that this is potentially an issue with header only libraries in general, but perhaps there is something you can do, as it used to work in previous versions.

**Comment by renatoGarcia** [comment]
@mrjackbo  Fixed. Thanks for catch that!
